site_name: shell-command-logger
theme:
  name: material
  custom_dir: overrides
  palette:
    # Dark theme
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # Light theme
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

plugins:
- badges
- search
- git-revision-date

nav:
- index.md
- installation.md
- configuration.md
- output-files.md
- "Logging commands":
  - log/manual.md
  - log/aliases.md
  - log/symlinks.md
  - log/shebang.md
- todo.md
- "Web site credits": created-with.md

markdown_extensions:
  # Allows page specific configurations (like hiding certain elements, setting the title, etc)
  - meta
