#!/usr/bin/env python3
import sys
# import the code from this package
from shell_command_logger.recorder import main_recorder

if __name__ == "__main__":
    command = sys.argv[1:]
    exit_code = main_recorder(command, __file__)
    sys.exit(exit_code)

